# Generated by Django 5.2 on 2025-04-27 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='cantidad_evaluaciones',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='eximicion',
            field=models.FloatField(default=5.3),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
